validation.email.api-key=f1fa5825285148d2904c6c242a293ad3
validation.email.base-url=https://emailreputation.abstractapi.com/v1/
validation.address.api-key=UA99-XW38-HU72-BX52
validation.address.url=https://api.addressy.com/Capture/Interactive/Find/v1.10/json3.ws